apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend-deployment
  labels:
    app: admin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
      - name: admin-frontend-container
        image: admin-dashboard
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 5174
          name: admin-ui-http
        env:
        - name: VITE_BACKEND_SERVER_URL
          value: "http://admin-service:80"
