apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer-container
        image: consumer-service
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 3003
          name: cons-http
        env:
        - name: TZ
          value: "Asia/Kolkata"
        - name: PORT
          value: "3003"
        - name: NODE_ENV
          value: "production"
        - name: PHARMA_CORE_URL
          value: "http://pharma-core-service:80"
        - name: SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: SERVICE_TOKEN
        - name: JWT_SECRET
          value: "fbf90411fe9cebf9079d22ef36fc1321f0ce244ed073152e86dc962715389b703463f6f163953269c641c9cd69ba3fd7c4b3f3a97a5305811c3d3c38608554cd"
        - name: GOOGLE_CLIENT_ID_WEB
          value: "465391349595-u9juj323k2l5r21is3lnfe9ue6dtjr7n.apps.googleusercontent.com"
        - name: GOOGLE_CLIENT_SECRET_WEB
          value: "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"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: CONSUMER_MONGO_URI
