import { DashboardStats, ManufacturerRecord, ShopkeeperRecord, AuditLogEntry, AdminUser } from '../../types/admin';

export const MOCK_ADMIN_USER: AdminUser = {
  adminId: 'ADM_01_VERMA',
  email: 'admin@pharmachain.gov.in',
  fullName: 'Dr. A. K. Verma',
  department: 'CDSCO Central Drug Inspectorate',
  role: 'SUPERADMIN',
  createdAt: '2026-01-10T08:00:00Z',
};

export const MOCK_STATS: DashboardStats = {
  manufacturers: { total: 14, pending: 3, approved: 10, rejected: 1 },
  shopkeepers: { total: 48, pending: 7, approved: 38, rejected: 2, suspended: 1 },
  cryptography: { activeKeys: 10, algorithm: 'ECDSA P-256 (SHA-256)' },
  urgentActionRequired: 10,
};

export const MOCK_MANUFACTURERS: ManufacturerRecord[] = [
  {
    manufacturerId: 'MFR_CIPLA_001_A3F',
    companyName: 'Cipla Pharmaceuticals India Ltd.',
    licenseNumber: 'MH-TZ1-284910',
    email: 'regulatory@cipla.com',
    kycStatus: 'PENDING',
    createdAt: '2026-08-23T09:30:00Z',
    hasSigningKey: false,
    state: 'Maharashtra',
    directorName: 'Dr. Umang Vohra',
    plantAddress: 'Plot No. 9, Patalganga Industrial Area, Raigad, Maharashtra 410220',
  },
  {
    manufacturerId: 'MFR_SUNPHARMA_002_B91',
    companyName: 'Sun Pharma Laboratories',
    licenseNumber: 'GJ-GNR-992104',
    email: 'compliance@sunpharma.com',
    kycStatus: 'PENDING',
    createdAt: '2026-08-23T11:15:00Z',
    hasSigningKey: false,
    state: 'Gujarat',
    directorName: 'Dilip Shanghvi',
    plantAddress: 'Halol-Baroda Highway, Halol, Gujarat 389350',
  },
  {
    manufacturerId: 'MFR_ALKEM_004_C52',
    companyName: 'Alkem Laboratories Ltd.',
    licenseNumber: 'HP-SOL-774910',
    email: 'regulatory@alkem.com',
    kycStatus: 'PENDING',
    createdAt: '2026-08-23T13:45:00Z',
    hasSigningKey: false,
    state: 'Himachal Pradesh',
    directorName: 'Sandeep Singh',
    plantAddress: 'Village Thana, Baddi, Solan, Himachal Pradesh 173205',
  },
  {
    manufacturerId: 'MFR_DRREDDY_003_K77',
    companyName: "Dr. Reddy's Laboratories Ltd.",
    licenseNumber: 'TS-HYD-551029',
    email: 'auth@drreddys.com',
    kycStatus: 'APPROVED',
    createdAt: '2026-08-20T14:00:00Z',
    hasSigningKey: true,
    publicKeyPem: `-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9Jc4H8WzQ2K1vNx7Lm9P4R8sTuVwXyZa\nBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg==\n-----END PUBLIC KEY-----`,
    state: 'Telangana',
    directorName: 'G. V. Prasad',
    plantAddress: 'Survey No. 42, Bachupally, Qutbullapur, Hyderabad 500090',
  },
  {
    manufacturerId: 'MFR_GSK_005_E88',
    companyName: 'GlaxoSmithKline Pharmaceuticals India Ltd.',
    licenseNumber: 'MH-THN-334102',
    email: 'compliance.india@gsk.com',
    kycStatus: 'APPROVED',
    createdAt: '2026-08-18T10:00:00Z',
    hasSigningKey: true,
    publicKeyPem: `-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7Ab1C2D3E4F5A6B7C8D9E0F1A2B3C4D5\nE6F7A8B9C0D1E2F3A4B5C6D7E8F9A0B1C2D3E4F5A6B7C8D9E0F1A2B3C4==\n-----END PUBLIC KEY-----`,
    state: 'Maharashtra',
    directorName: 'Bhushan Akshikar',
    plantAddress: 'Thane-Belapur Road, Navi Mumbai 400705',
  },
  {
    manufacturerId: 'MFR_FAKECO_999_X00',
    companyName: 'Apex Chem & Drugs Pvt Ltd',
    licenseNumber: 'DL-WDL-001928',
    email: 'info@apexchem.fake',
    kycStatus: 'REJECTED',
    createdAt: '2026-08-21T08:00:00Z',
    hasSigningKey: false,
    rejectionReason: 'Invalid drug manufacturing license; not listed in State Licensing Authority portal. Fictitious manufacturing unit address.',
    state: 'Delhi',
    directorName: 'Unknown Applicant',
    plantAddress: 'Plot 4, Nangloi Extn, New Delhi 110041',
  },
];

export const MOCK_SHOPKEEPERS: ShopkeeperRecord[] = [
  {
    shopId: 'SHOP-8B1A2C3D',
    shopName: 'Apollo Pharmacy — Connaught Place',
    shopPhone: '+91 11 4321 0000',
    shopEmail: 'cp.delhi@apollopharmacy.in',
    address: 'Block E, Inner Circle, Connaught Place',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110001',
    ownerName: 'Virender Sharma',
    ownerPhone: '+91 98112 34567',
    ownerEmail: 'virender.sharma@gmail.com',
    drugLicenseNumber: 'DL-ND-2024-004128',
    licenseType: 'retail',
    issuingAuthority: 'Drugs Control Department, Govt. of NCT Delhi',
    licenseIssueDate: '2024-01-15',
    licenseExpiryDate: '2029-01-14',
    documentUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    documentMeta: { name: 'Drug_License_Form_20_21.pdf', size: 1420000, mimeType: 'application/pdf' },
    verificationStatus: 'pending',
    createdAt: '2026-08-23T14:20:00Z',
  },
  {
    shopId: 'SHOP-3A9F1E2D',
    shopName: 'Noble Chemists & Druggists',
    shopPhone: '+91 22 2410 8899',
    shopEmail: 'noblechemists.mumbai@gmail.com',
    address: 'Shop 4, Dr. B. A. Road, Dadar TT Circle',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400014',
    ownerName: 'Rajesh K. Mehta',
    ownerPhone: '+91 98200 44556',
    ownerEmail: 'rajesh.mehta@noblechem.com',
    drugLicenseNumber: 'MH-MZ2-2023-901844',
    licenseType: 'retail',
    issuingAuthority: 'Food & Drugs Administration (FDA Maharashtra)',
    licenseIssueDate: '2023-04-10',
    licenseExpiryDate: '2028-04-09',
    documentUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    documentMeta: { name: 'FDA_MH_Form20_License.pdf', size: 1850000, mimeType: 'application/pdf' },
    verificationStatus: 'pending',
    createdAt: '2026-08-23T16:00:00Z',
  },
  {
    shopId: 'SHOP-7F9E0D1C',
    shopName: 'MedPlus Health Services Chemist',
    shopPhone: '+91 40 2345 6789',
    shopEmail: 'store412@medplusindia.com',
    address: 'Plot 42, Hitec City Main Road',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500081',
    ownerName: 'K. S. Rao',
    ownerPhone: '+91 99490 12345',
    ownerEmail: 'ksrao@medplus.in',
    drugLicenseNumber: 'TS-RR-2023-881902',
    licenseType: 'retail',
    issuingAuthority: 'Telangana State Drugs Control Administration',
    licenseIssueDate: '2023-06-10',
    licenseExpiryDate: '2028-06-09',
    documentUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    documentMeta: { name: 'TS_Form20B_21B.pdf', size: 2100000, mimeType: 'application/pdf' },
    verificationStatus: 'approved',
    verifiedAt: '2026-08-22T10:00:00Z',
    createdAt: '2026-08-22T09:00:00Z',
  },
  {
    shopId: 'SHOP-4D2A1B9E',
    shopName: 'Gupta Medicos Wholesale Depot',
    shopPhone: '+91 124 400 1122',
    shopEmail: 'guptamedicos@rediffmail.com',
    address: 'Shop 12, Old Railway Road',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122001',
    ownerName: 'Ramesh Gupta',
    ownerPhone: '+91 98120 99887',
    ownerEmail: 'ramesh.gupta@yahoo.com',
    drugLicenseNumber: 'HR-GGN-2022-771120',
    licenseType: 'wholesale',
    issuingAuthority: 'FDA Haryana',
    licenseIssueDate: '2022-03-01',
    licenseExpiryDate: '2027-02-28',
    documentUrl: null,
    documentMeta: null,
    verificationStatus: 'rejected',
    rejectionReason: 'Mandatory Form 20B/21B wholesale license scan not provided.',
    createdAt: '2026-08-21T16:00:00Z',
  },
  {
    shopId: 'SHOP-991A4F00',
    shopName: 'City Express Pharma Distributors',
    shopPhone: '+91 11 2399 7788',
    shopEmail: 'cityexpress@delhipharma.net',
    address: 'Bhagirath Palace, Chandni Chowk',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110006',
    ownerName: 'Sunil Aggarwal',
    ownerPhone: '+91 98100 11223',
    ownerEmail: 'sunil@delhipharma.net',
    drugLicenseNumber: 'DL-CZ-2021-440192',
    licenseType: 'wholesale',
    issuingAuthority: 'Drugs Control Department, Govt. of NCT Delhi',
    licenseIssueDate: '2021-02-15',
    licenseExpiryDate: '2026-02-14',
    documentUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    documentMeta: { name: 'DL_Wholesale_Certificate.pdf', size: 1200000, mimeType: 'application/pdf' },
    verificationStatus: 'suspended',
    rejectionReason: 'Emergency suspension: Flagged for distribution of unverified/recalled batch strips under CDSCO Notice #441.',
    createdAt: '2026-08-19T11:00:00Z',
  }
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    _id: 'LOG_001',
    action: 'MANUFACTURER_APPROVED',
    performedBy: { adminId: 'ADM_01_VERMA', fullName: 'Dr. A. K. Verma', email: 'admin@pharmachain.gov.in', role: 'SUPERADMIN' },
    targetType: 'MANUFACTURER',
    targetId: 'MFR_DRREDDY_003_K77',
    targetName: "Dr. Reddy's Laboratories Ltd.",
    metadata: { keyId: 'KEY_DRREDDY_P256_01', algorithm: 'ECDSA P-256', curve: 'secp256r1' },
    createdAt: '2026-08-20T14:02:10Z',
    ipAddress: '10.244.0.15',
  },
  {
    _id: 'LOG_002',
    action: 'SHOPKEEPER_APPROVED',
    performedBy: { adminId: 'ADM_01_VERMA', fullName: 'Dr. A. K. Verma', email: 'admin@pharmachain.gov.in', role: 'SUPERADMIN' },
    targetType: 'SHOPKEEPER',
    targetId: 'SHOP-7F9E0D1C',
    targetName: 'MedPlus Health Services Chemist',
    metadata: { licenseType: 'retail', validity: '2028-06-09' },
    createdAt: '2026-08-22T10:00:15Z',
    ipAddress: '10.244.0.15',
  },
  {
    _id: 'LOG_003',
    action: 'MANUFACTURER_REJECTED',
    performedBy: { adminId: 'ADM_01_VERMA', fullName: 'Dr. A. K. Verma', email: 'admin@pharmachain.gov.in', role: 'SUPERADMIN' },
    targetType: 'MANUFACTURER',
    targetId: 'MFR_FAKECO_999_X00',
    targetName: 'Apex Chem & Drugs Pvt Ltd',
    reason: 'Invalid drug manufacturing license; not listed in State Licensing Authority portal.',
    createdAt: '2026-08-21T08:15:00Z',
    ipAddress: '10.244.0.15',
  },
  {
    _id: 'LOG_004',
    action: 'SHOPKEEPER_SUSPENDED',
    performedBy: { adminId: 'ADM_01_VERMA', fullName: 'Dr. A. K. Verma', email: 'admin@pharmachain.gov.in', role: 'SUPERADMIN' },
    targetType: 'SHOPKEEPER',
    targetId: 'SHOP-991A4F00',
    targetName: 'City Express Pharma Distributors',
    reason: 'Emergency suspension: Flagged for distribution of unverified/recalled batch strips under CDSCO Notice #441.',
    createdAt: '2026-08-23T08:30:00Z',
    ipAddress: '10.244.0.15',
  }
];
